### ISSUE TITLE
Return usecase errors in defaultResolver

### ISSUE THREAD

**Issue by italojs** [herbsjs/herbs2gql#23]
### 1
Recently I needed to return an custom error to my API requester but to do it I needed to implement my own resolver, the problem here is that my resolver is identical to [defaultResolver](https://github.com/herbsjs/herbs2gql/blob/master/src/defaultResolver.js), the unique difference is the error handler

### 2

I would like to return the error in my own pattern, e.g { message, code, stacktrace }, but i cant do it with defaultResolver because it forces to return a fix error format (`result.err` only)

## Problem
In defaultResolver we are returning an [userInputError](https://github.com/herbsjs/herbs2gql/blob/f4cb0f51f136c7a3e7e2c97f35d02d0b5ed794e9/src/defaultResolver.js#L28) every time the usecase return an Err, buuuuut my usecase can return an Err for many reasons that not includes the user input

defaultResolver.js
``` js
[...]
        const request = args2request(args, uc)
        const response = await uc.run(request)

        // eslint-disable-next-line no-console
        console.info(uc.auditTrail)

        /* I dont have another option to return an Err to my api-requester */
        if (response.isErr) throw new UserInputError(null, { invalidArgs: response.err })
        return response.ok
[...]
```
## solution

defaultResolver.js
``` js
function defaultResolver(usecase, errorHandler) {
[...]
        const request = args2request(args, uc)
        const response = await uc.run(request)

        // eslint-disable-next-line no-console
        console.info(uc.auditTrail)

        /* using the await because if this function be async, we dont will problem with  */
        if(response.isErr && errorCallback) return await errorHandler(response.err)
         // I still believe we can remove this UserInputError but i'm not sure if this can broke others apps
        if (response.isErr) throw new UserInputError(null, { invalidArgs: response.err })
        return response.ok
[...]
```
my gql app
``` js
// it can be async or not
function errorHandler(err) {
     // here I'm free to handler MYYY errors like I need
      return new ApolloError(err.message, err.code, err.stackTrace)
}
const mutations = usecases.map(usecase => usecase2mutation(usecase, defaultResolver(usecase, errorHandler)))
```

**Comment by dalssoft** [comment]
Is there an open issue to doc it on herbs site/doc?
