### ISSUE TITLE
Error using a entity as a field of another entity

### ISSUE THREAD

**Issue by Vx-Nico** [herbsjs/herbs2gql#43]
**Describe the bug**
When I use a entity as a field of another entity, for some reason it threw an Unknow type error.

**To Reproduce**
Create an entity 
Import this entity into another entity
Use this imported entity as a field

example:
```
const { field, entity } = require('@herbsjs/herbs')
const B = require('../entities')

const A = entity("A", {
    B: field(B)
})

module.exports = A
```

Update the entities index

example:
```
module.exports = {
    A: require('./A'),
    B: require('./B')
}
```

Check the log when you run the application

**Expected behavior**
Graphql should create type and input without error

**Screenshots**
![imagem erro](https://user-images.githubusercontent.com/85580539/162794182-ec161435-cfc1-4143-88df-96675d7e2a08.png)

**Comment by Vx-Nico** [comment]
I updated the screenshot, see if is clearer now

**Comment by anahelenasilva** [comment]
I had the same issue as @Vx-Nico when doing the same thing

**Comment by italojs** [comment]
do you have a solution to propose for this problem? 
if not, could you provide a sample/full/simple script for us reproduce the error and try to solve the problem?

**Comment by dalssoft** [comment]
Checking the current tests it seems there is no implementation/support for entity fields with types of entities and entities arrays. The only place that I could find support is here:

https://github.com/herbsjs/herbs2gql/blob/master/test/usecase2query.test.js#L180
https://github.com/herbsjs/herbs2gql/blob/master/test/usecase2subscription.test.js#L267

However it should not be difficult to implement. PRs are welcome.
