### ISSUE TITLE
Add dependencies of the lib from devDependencies to peerDependencies

### ISSUE THREAD

**Issue by jhomarolo** [herbsjs/herbs2gql#52]
**Is your feature request related to a problem? Please describe.**
Some dependencies of the lib like ( graphql, apollo etc) are listed as devDependencies, but are a peerDependencies as well (https://nodejs.org/es/blog/npm/peer-dependencies/) and should be added in this section too

**Describe the solution you'd like**
Like herbs2knex(https://github.com/herbsjs/herbs2knex/blob/master/package.json) the lib should list the peer dependency

**Comment by mtperesvx** [comment]
I can work on it.
